In [1]:
#!pip install padelpy
#https://github.com/ecrl/padelpy

Collecting padelpy
  Downloading padelpy-0.1.14-py2.py3-none-any.whl.metadata (7.7 kB)
Downloading padelpy-0.1.14-py2.py3-none-any.whl (20.9 MB)
   ---------------------------------------- 20.9/20.9 MB 12.3 MB/s eta 0:00:00
Installing collected packages: padelpy
Successfully installed padelpy-0.1.14

DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

In [3]:
from padelpy import from_smiles

# calculate molecular descriptors for propane
descriptors = from_smiles('C(C(=O)O)Cl')

# calculate molecular descriptors for propane and butane
descriptors = from_smiles(['C(C(=O)O)Cl', 'CCCC'])

# in addition to descriptors, calculate PubChem fingerprints
desc_fp = from_smiles('C(C(=O)O)Cl', fingerprints=True)

# only calculate fingerprints
fingerprints = from_smiles('C(C(=O)O)Cl', fingerprints=True, descriptors=False)

# setting the number of threads, this uses one cpu thread to compute descriptors
descriptors = from_smiles(['C(C(=O)O)Cl', 'CCCC'], threads = 1)

# save descriptors to a CSV file
_ = from_smiles('C(C(=O)O)Cl', output_csv='descriptors.csv')

In [5]:
import pandas as pd

file_path = 'data_from_paper.xlsx'

xl = pd.ExcelFile(file_path)

sheet_names = xl.sheet_names

sheet_name = 'Descriptors(1-187)-PaDEL'

data_df = xl.parse(sheet_name)
data_df

,Unnamed: 0,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,...,AMW,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb
0,1,0,-0.6854,0.469773,16.0871,11.416344,0,0,12,4,...,5.004793,6.871320,1.717830,2.310660,2.310660,0.00000,10,1,0.282,10
1,2,0,0.9449,0.892836,10.8232,7.301172,0,0,8,4,...,8.253513,6.732051,1.683013,4.488034,0.000000,0.00000,9,0,1.542,12
2,3,0,-0.9734,0.947508,18.9987,14.509930,0,0,15,5,...,4.938211,8.849874,1.769975,2.362437,2.362437,0.00000,20,2,0.851,14
3,4,0,-0.6961,0.484555,20.6715,14.509930,0,0,15,5,...,4.938211,8.696802,1.739360,2.313053,2.313053,0.00000,18,2,0.742,16
4,5,0,0.1242,0.015426,21.5446,14.509930,0,0,15,5,...,4.938211,8.696802,1.739360,2.329115,2.329115,0.00000,18,2,0.579,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,183,0,0.0211,0.000445,17.4128,10.884758,0,0,11,5,...,6.730616,8.696802,1.739360,4.899812,4.899812,0.00000,18,2,0.241,16
183,184,0,-1.1870,1.408969,16.2111,10.089551,0,0,11,4,...,5.550251,6.871320,1.717830,4.621320,2.310660,2.31066,10,1,-1.275,10
184,185,0,-0.5281,0.278890,23.7679,14.943137,0,0,15,6,...,5.804561,11.812500,1.968750,5.875000,2.937500,2.93750,27,3,-0.576,24
185,186,0,5.1662,26.689622,49.8066,47.827032,0,0,37,13,...,6.381308,23.625608,1.817354,15.358678,5.652951,0.00000,248,12,4.392,64
186,187,0,-0.1854,0.034373,14.7090,10.614344,0,0,11,3,...,4.005691,4.914214,1.638071,0.000000,0.000000,0.00000,4,0,2.047,6

In [7]:
import pandas as pd

file_path = 'descriptors.csv'

idata_df = pd.read_csv(file_path)

idata_df

,Name,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,...,P1s,P2s,E1s,E2s,E3s,Ts,As,Vs,Ks,Ds
0,AUTOGEN_20240506124102306563655465475,1,0.3027,0.091627,17.3969,9.304379,0,0,8,5,...,0.535836,0.391228,0.379021,0.489006,0.195982,2.506282,1.741536,4.488529,0.390595,1.064008

In [28]:
import pandas as pd

file_path = 'gwp3.xlsx'

xl = pd.ExcelFile(file_path)

sheet_names = xl.sheet_names

sheet_name = 'GWP_data'

data_dfg = xl.parse(sheet_name)
data_dfg['GWP'] = data_dfg['GWP'].str.replace(' ', '')

data_dfg['GWP'] = data_dfg['GWP'].apply(lambda x: float(x) if isinstance(x, str) else x)


data_dfg

        GWP
0     4.440
1     6.400
2     2.900
3     4.290
4     2.900
..      ...
182   2.870
183   9.530
184  15.500
185   0.828
186   4.900

[187 rows x 1 columns]

In [29]:
nan_values = data_dfg['GWP'].isna().any()
nan_values
nan_indices = data_dfg[data_dfg['GWP'].isna()].index
nan_indices

Int64Index([], dtype='int64')

In [30]:
data_df['GWP'] = data_dfg['GWP']
data_df

,Unnamed: 0,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,...,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb,GWP
0,1,0,-0.6854,0.469773,16.0871,11.416344,0,0,12,4,...,6.871320,1.717830,2.310660,2.310660,0.00000,10,1,0.282,10,4.440
1,2,0,0.9449,0.892836,10.8232,7.301172,0,0,8,4,...,6.732051,1.683013,4.488034,0.000000,0.00000,9,0,1.542,12,6.400
2,3,0,-0.9734,0.947508,18.9987,14.509930,0,0,15,5,...,8.849874,1.769975,2.362437,2.362437,0.00000,20,2,0.851,14,2.900
3,4,0,-0.6961,0.484555,20.6715,14.509930,0,0,15,5,...,8.696802,1.739360,2.313053,2.313053,0.00000,18,2,0.742,16,4.290
4,5,0,0.1242,0.015426,21.5446,14.509930,0,0,15,5,...,8.696802,1.739360,2.329115,2.329115,0.00000,18,2,0.579,16,2.900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,183,0,0.0211,0.000445,17.4128,10.884758,0,0,11,5,...,8.696802,1.739360,4.899812,4.899812,0.00000,18,2,0.241,16,2.870
183,184,0,-1.1870,1.408969,16.2111,10.089551,0,0,11,4,...,6.871320,1.717830,4.621320,2.310660,2.31066,10,1,-1.275,10,9.530
184,185,0,-0.5281,0.278890,23.7679,14.943137,0,0,15,6,...,11.812500,1.968750,5.875000,2.937500,2.93750,27,3,-0.576,24,15.500
185,186,0,5.1662,26.689622,49.8066,47.827032,0,0,37,13,...,23.625608,1.817354,15.358678,5.652951,0.00000,248,12,4.392,64,0.828
186,187,0,-0.1854,0.034373,14.7090,10.614344,0,0,11,3,...,4.914214,1.638071,0.000000,0.000000,0.00000,4,0,2.047,6,4.900

In [31]:
data_df = data_df.drop('Unnamed: 0', axis=1)
data_df

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb,GWP
0,0,-0.6854,0.469773,16.0871,11.416344,0,0,12,4,8,...,6.871320,1.717830,2.310660,2.310660,0.00000,10,1,0.282,10,4.440
1,0,0.9449,0.892836,10.8232,7.301172,0,0,8,4,4,...,6.732051,1.683013,4.488034,0.000000,0.00000,9,0,1.542,12,6.400
2,0,-0.9734,0.947508,18.9987,14.509930,0,0,15,5,10,...,8.849874,1.769975,2.362437,2.362437,0.00000,20,2,0.851,14,2.900
3,0,-0.6961,0.484555,20.6715,14.509930,0,0,15,5,10,...,8.696802,1.739360,2.313053,2.313053,0.00000,18,2,0.742,16,4.290
4,0,0.1242,0.015426,21.5446,14.509930,0,0,15,5,10,...,8.696802,1.739360,2.329115,2.329115,0.00000,18,2,0.579,16,2.900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,0,0.0211,0.000445,17.4128,10.884758,0,0,11,5,6,...,8.696802,1.739360,4.899812,4.899812,0.00000,18,2,0.241,16,2.870
183,0,-1.1870,1.408969,16.2111,10.089551,0,0,11,4,7,...,6.871320,1.717830,4.621320,2.310660,2.31066,10,1,-1.275,10,9.530
184,0,-0.5281,0.278890,23.7679,14.943137,0,0,15,6,9,...,11.812500,1.968750,5.875000,2.937500,2.93750,27,3,-0.576,24,15.500
185,0,5.1662,26.689622,49.8066,47.827032,0,0,37,13,24,...,23.625608,1.817354,15.358678,5.652951,0.00000,248,12,4.392,64,0.828
186,0,-0.1854,0.034373,14.7090,10.614344,0,0,11,3,8,...,4.914214,1.638071,0.000000,0.000000,0.00000,4,0,2.047,6,4.900

In [32]:
data_df.to_csv('data_GWP_atoms.csv', sep=',', index=False)

In [35]:
data_df

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb,GWP
0,0,-0.6854,0.469773,16.0871,11.416344,0,0,12,4,8,...,6.871320,1.717830,2.310660,2.310660,0.00000,10,1,0.282,10,4.440
1,0,0.9449,0.892836,10.8232,7.301172,0,0,8,4,4,...,6.732051,1.683013,4.488034,0.000000,0.00000,9,0,1.542,12,6.400
2,0,-0.9734,0.947508,18.9987,14.509930,0,0,15,5,10,...,8.849874,1.769975,2.362437,2.362437,0.00000,20,2,0.851,14,2.900
3,0,-0.6961,0.484555,20.6715,14.509930,0,0,15,5,10,...,8.696802,1.739360,2.313053,2.313053,0.00000,18,2,0.742,16,4.290
4,0,0.1242,0.015426,21.5446,14.509930,0,0,15,5,10,...,8.696802,1.739360,2.329115,2.329115,0.00000,18,2,0.579,16,2.900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,0,0.0211,0.000445,17.4128,10.884758,0,0,11,5,6,...,8.696802,1.739360,4.899812,4.899812,0.00000,18,2,0.241,16,2.870
183,0,-1.1870,1.408969,16.2111,10.089551,0,0,11,4,7,...,6.871320,1.717830,4.621320,2.310660,2.31066,10,1,-1.275,10,9.530
184,0,-0.5281,0.278890,23.7679,14.943137,0,0,15,6,9,...,11.812500,1.968750,5.875000,2.937500,2.93750,27,3,-0.576,24,15.500
185,0,5.1662,26.689622,49.8066,47.827032,0,0,37,13,24,...,23.625608,1.817354,15.358678,5.652951,0.00000,248,12,4.392,64,0.828
186,0,-0.1854,0.034373,14.7090,10.614344,0,0,11,3,8,...,4.914214,1.638071,0.000000,0.000000,0.00000,4,0,2.047,6,4.900